cora_cite:
  drop_incidence_rate: 0.3
  drop_feature_rate: 0.3
  tau_n: 0.5
  tau_g: 0.5
  tau_m: 1.0
  w_g: 4
  w_m: 1  
  lr: 0.001
  batch_size_1: null
  batch_size_2: null
  hid_dim: 512
  proj_dim: 128
  weight_decay: 1.0e-06
  num_layers: 2
  epochs: 200
  

citeseer_cite:
  drop_incidence_rate: 0.4
  drop_feature_rate: 0.2
  tau_n: 1.0
  tau_g: 1.0
  tau_m: 0.8
  w_g: 4
  w_m: 2
  lr: 0.0001
  batch_size_1: null
  batch_size_2: null
  hid_dim: 256
  proj_dim: 128
  weight_decay: 1.0e-06
  num_layers: 2
  epochs: 200
  batch_size_1: null
  batch_size_2: null

pubmed_cite:

  lr: 5.0e-04
  drop_feature_rate: 0.1
  drop_incidence_rate: 0.4
  tau_n: 0.3
  tau_g: 0.2
  tau_m: 0.6
  w_g: 4
  w_m: 2
  hid_dim: 128
  proj_dim: 128
  weight_decay: 1.0e-06
  num_layers: 2
  epochs: 200
  batch_size_1: null
  batch_size_2: 4096

cora_coauth:
  drop_incidence_rate: 0.4
  drop_feature_rate: 0.2
  tau_n: 0.6
  tau_g: 0.5
  tau_m: 0.1
  w_g: 0.5
  w_m: 0.5
  lr: 0.001
  hid_dim: 512
  proj_dim: 256
  weight_decay: 1.0e-06
  num_layers: 2
  epochs: 200
  batch_size_1: null
  batch_size_2: null

dblp_copub:
  drop_incidence_rate: 0.3
  drop_feature_rate: 0.3
  tau_n: 0.8
  tau_g: 0.6
  tau_m: 0.7
  w_g: 2
  w_m: 1
  lr: 0.001
  hid_dim: 128
  proj_dim: 128
  weight_decay: 1.0e-06
  num_layers: 2
  epochs: 200
  batch_size_1: 4096
  batch_size_2: 1024

news:
  drop_incidence_rate: 0.4
  drop_feature_rate: 0.1
  tau_n: 1
  tau_g: 0.8
  tau_m: 1.0
  w_g: 0.0625
  w_m: 0.0625
  lr: 0.0001
  hid_dim: 128
  proj_dim: 128
  weight_decay: 1.0e-06
  num_layers: 2
  epochs: 200
  batch_size_1: null
  batch_size_2: 8192

modelnet_40:
  drop_incidence_rate: 0.4
  drop_feature_rate: 0
  tau_n: 0.9
  tau_g: 0.3
  tau_m: 0.9
  w_g: 0.25
  w_m: 0.125
  lr: 0.0001
  hid_dim: 128
  proj_dim: 128
  weight_decay: 1.0e-06
  num_layers: 2
  epochs: 200
  batch_size_1: null
  batch_size_2: 8192

aminer:
  drop_incidence_rate: 0.5
  drop_feature_rate: 0.2
  tau_n: 0.6
  tau_g: 0.7
  tau_m: 1.0
  w_g: 1
  w_m: 0.0625
  lr: 0.0005
  hid_dim: 256
  proj_dim: 128
  weight_decay: 1.0e-06
  num_layers: 2
  epochs: 200
  batch_size_1: null
  batch_size_2: 8192

  
imdb:
  drop_incidence_rate: 0.6
  drop_feature_rate: 0.7
  tau_n: 0.1
  tau_g: 0.3
  tau_m: 0.9
  w_g: 4
  w_m: 0.5
  lr: 0.001
  hid_dim: 256
  proj_dim: 128
  weight_decay: 1.0e-06
  num_layers: 2
  epochs: 200
  batch_size_1: null
  batch_size_2: null
  #  task: edge

house:
  drop_incidence_rate: 0.7
  drop_feature_rate: 0.5
  tau_n: 0.3
  tau_g: 0.9
  tau_m: 0.8
  w_g: 0.25
  w_m: 2
  lr: 0.001
  hid_dim: 256
  proj_dim: 128
  weight_decay: 1.0e-06
  num_layers: 2
  epochs: 200
  batch_size_1: null
  batch_size_2: null


dblp_coauth:
  drop_incidence_rate: 0.2
  drop_feature_rate: 0.2
  tau_n: 0.2
  tau_g: 0.2
  tau_m: 0.6
  w_g: 2
  w_m: 4
  lr: 0.001
  hid_dim: 256
  proj_dim: 128
  weight_decay: 1.0e-06
  num_layers: 2
  epochs: 200
  batch_size_1: 4096
  batch_size_2: 1024